@Library('jenkinslib') _
def dockerfileContent = libraryResource 'angular.dockerfile'
writeFile file: 'Dockerfile', text: dockerfileContent

buildAndDeploy(
    image: 'angular-docker',
    registry: 'pisethsattya',
    tag: '1.3',
    containerPort: '80',
    hostPort: '8081'
)