@Library('jenkinslib') _

buildAndDeploy(
    image: 'angular-docker',
    registry: 'pisethsattya',
    tag: '1.3',
    containerPort: '80',
    hostPort: '8081'
)
  pipeline {
        agent any

        stages {
            stage('Git Clone') {
                steps {
                    git branch: 'main', url: 'https://github.com/SattyaPiseth/jenkins-with-angular.git'
                }
            }

            stage('Build Docker Image') {
                steps {
                    script {
                        echo "Building Docker image: ${registry}/${image}:${tag}"
                        sh """
                            docker build -t ${registry}/${image}:${tag} .
                            docker rm -f ${image}
                        """
                    }
                }
            }

            stage('Docker hub login'){
                steps{
                    script{
                        withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                            sh """
                                docker login -u ${USER} -p ${PASS}
                                docker push ${registry}/${image}:${tag}
                            """
                        }
                    }
                }
            }

            stage('Deploy Docker Container') {
                steps {
                    script {
                        echo "Deploying Docker container: ${registry}/${image}:${tag}"
                        sh """
                            docker run -d -p ${hostPort}:${containerPort} --name ${image} ${registry}/${image}:${tag}
                        """
                    }
                }
            }
        }
    }